# Source: https://medium.com/@Keithweaver_/setting-up-github-actions-for-a-react-app-on-github-pages-f66b28c312ac
name: MasterDeployCI
on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "6730539+carmayna@users.noreply.github.com"
          git config --global user.name "MasterDeployCI"
          git remote set-url origin https://${{ secrets.githubApiToken }}@github.com/covid19-apptracker/covid19-apptracker.git
          npm run deploy
        env:
          CI: ""
      - name: Updating Domain
        run: echo "Update domain"
